version: 2

builds:
  - id: default
    goos:
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.appVersion={{.Version}}
    binary: water
